---
title: "Germination of alpine focal species - dataset vi - Survival"
output: html_notebook
author: "Sonya R. Geange"
---


```{r load_packages_data}
library(osfr)
library(dataDownloader)
library(lubridate)
library(tidyverse)

# Get data from OSF Account

# osf_auth(token = "add OSF PAT Token Here") 

# Download 
# get_file(node = "zhk3m",
#          file = "INCLINE_seedling_data.csv",
#          path = "data/Germination_field_experiment",
#          remote_path = "RawData/Germination_field_experiment")

#### Load data ####

# Read in dataset
data <- read.csv2("Data/Germination_field_experiment/INCLINE_seedling_data.csv", header = TRUE)

```



# Clean Dataset

```{r}

# What data types do we have?
str(data)

# Correct dataset elements
seedling_survival <- data %>%
  rename(species = Species,
         registrator = Registrator) %>% 
  mutate(Block = as.character(Block)) %>% 
  mutate(site = case_when(Site == "LAV" ~ "Lav",
                          Site == "ULV" ~ "Ulv",
                          Site == "GUD" ~ "Gud",
                          Site == "SKJ" ~ "Skj")) %>%
  mutate(siteID = case_when(Site == "LAV" ~ "Lavisdalen",
                            Site == "ULV" ~ "Ulvehaugen",
                            Site == "GUD" ~ "Gudmedalen",
                            Site == "SKJ" ~ "Skjellingahaugen")) %>%
# Fix error for ULV_5_OTC where Plot and PlotID appear switched
# PlotID should be ULV_5_OTC whereas Plot should be just OTC
    mutate(PlotID = ifelse(site == "Ulv" & Block == "5" & Plot == "5" & PlotID == "OTC" & species == "Ver_alp","ULV_5_OTC", PlotID)) %>% 
      mutate(Plot = ifelse(PlotID == "ULV_5_OTC" & species == "Ver_alp", "OTC", Plot)) %>% 
# Rename levels of variables and create ID columns
      mutate(OTC = ifelse(Warm_treatment == "C", "C",
                        ifelse(Warm_treatment == "W", "W", Plot))) %>% 
      mutate(OTC = case_when(OTC == "W" ~ "W",
                          OTC == "C" ~ "C",
                          OTC == "OTC" ~ "W")) %>%
  mutate(vegetation = case_when(Vegetation == "no" ~ "NoVeg",
                          Vegetation == "yes" ~ "Veg")) %>%
  mutate(blockID = paste0(site, "_", Block)) %>% 
  # Define if experiment is from the germination trial (E) or background demography monitoring (B)
  mutate(experiment = ifelse(Plot == "OTC"|Plot == "C","E","B")) %>% 
  mutate(plotID = paste0(blockID, "_", experiment, "_",
                                   OTC, "_", vegetation)) %>%
  mutate(uniqueID = paste0(species, "_",
                           blockID, "_", experiment, "_",
                           OTC, "_", vegetation, "_", ID)) %>%
  mutate(date = as.Date(Date, format = "%d.%m.%Y")) %>%
# To fix: We have two rows where "2021-06-26" is found, but this doesn't correspond to any field trips planned that season. We assume it's a mistake and should be "2021-08-06" and therefore campaign 7.
    mutate(campaign_number = 
           if_else(date == "2020-06-29" | 
                   date == "2020-06-30" | 
                   date == "2020-07-13" | 
                   date == "2020-07-14" |
                   date == "2020-07-17", "first",
           if_else(date == "2020-08-05" | date == "2020-08-07" |
                   date == "2020-08-12" | date == "2020-08-13" |
                   date == "2020-08-14", "second",
           if_else(date == "2020-08-26" | date == "2020-08-24" |
                   date == "2020-08-25" | date == "2020-08-27", "third",
           if_else(date == "2021-06-07" | date == "2021-06-08" |
                   date == "2021-06-09" | date == "2021-06-10" |
                   date == "2021-06-11", "fourth", 
           if_else(date == "2021-07-05" | date == "2021-07-06" |
                   date == "2021-07-07" | date == "2021-07-08" |
                   date == "2021-07-09" | date == "2021-07-12",
                   "fifth",
           if_else(date == "2021-08-02" | date == "2021-08-03" |
                   date == "2021-08-04" | date == "2021-08-05" | 
                   date == "2021-08-06", "sixth",
           if_else(date == "2021-08-26" | date == "2021-08-27" |
                   date == "2021-08-28" | date == "2021-08-29" |
                   # Error fixing
                   date == "2021-06-26",
                   "seventh",
                   "NA")))))))) %>% 
  # Some Gudemedalen blocks/plots were not able to be sampled because of snow, so a trip zero is logged in June, with first trip then in July instead. 
        mutate(campaign_number = if_else(PlotID == "G_2_C" & 
                                           date == "2020-06-29", "zero",
            if_else(PlotID == "G_2_C" & date == "2020-06-30", "zero",
            if_else(PlotID == "G_2_C" & date == "2020-07-17", "first",
            if_else(PlotID == "G_2_C" & date == "2020-08-13", "second",
            if_else(PlotID == "G_2_C" & date == "2020-08-26", "third",
            if_else(PlotID == "G_2_OTC" & date == "2020-06-29", "zero",
            if_else(PlotID == "G_2_OTC" & date == "2020-06-30", "zero",
            if_else(PlotID == "G_2_OTC" & date == "2020-07-17", "first",
            if_else(PlotID == "G_2_OTC" & date == "2020-08-13", "second",
            if_else(PlotID == "G_2_OTC" & date == "2020-08-26", "third", campaign_number))))))))))) %>% 
  rename(present = Present,
         vegetation_height = Veg_height,
         bryophyte_depth = Moss_depth,
         vegetation_cover = Veg_cover,
         bryophyte_cover = Moss_cover,
         lichen_cover = Lichen_cover,
         comments = Comment) %>% 
  select(species, siteID, blockID, experiment, OTC, vegetation,
         plotID, uniqueID, registrator,
         date, campaign_number, 
         X, Y, present, vegetation_height, bryophyte_depth, vegetation_cover,
         bryophyte_cover, lichen_cover, comments)

# ISSUES: 
# We have a couple of cases where there are multiple measures on 'present' for an individual for a given campaign.
# Also, for each individual there is up to 7 campaigns where it could have been present, yet we do not have seven campaigns per individual.
# Individuals may also be present in campaign 5, not in 6 and 'reappear' in 8.

# Issues are identified with multiple cell values or NULL
seedling_survival_wide <- seedling_survival %>% 
  select(uniqueID, campaign_number, present) %>%
  distinct() %>% 
  pivot_wider(
  id_cols = uniqueID,
  names_from = campaign_number,
  values_from = present) %>% 
  select(uniqueID, zero, first, second, third, fourth, fifth, sixth, seventh)

# Issues with multiple cell values:
# We still have "Ver_alp_Gud_5_E_W_NoVeg_16": This has 2 times campaign 3 records, one yes one no, same date and registrar (you)- It is considered present only in  campaign 2, in one of the two records for campaign 3 and also in campaign 4. Looking at raw data should be 'yes' campaign three. 
seedling_survival <- seedling_survival %>% 
  mutate(present = ifelse(uniqueID == "Ver_alp_Gud_5_E_W_NoVeg_16" & 
                            campaign_number == "third","yes", present))

# Check again
seedling_survival_wide <- seedling_survival %>% 
  select(uniqueID, campaign_number, present) %>%
  distinct() %>% 
  pivot_wider(
  id_cols = uniqueID,
  names_from = campaign_number,
  values_from = present) %>% 
  select(uniqueID, zero, first, second, third, fourth, fifth, sixth, seventh)

# Clean blanks - assume = no
seedling_survival_wide <- seedling_survival_wide %>% 
  replace_na(list(zero = "no", first = "no", second = "no",
                  third = "no", fourth = "no", fifth = "no",
                  sixth = "no", seventh = "no"))

# Back to long format
seedling_survival_long <- seedling_survival_wide %>% 
  pivot_longer(!uniqueID,
               names_to = "campaign_number",
               values_to = "present")

# Merge with full data set for meta-data
seedling_data_sub <- seedling_survival %>%
  select(-c(present))
full_data <- left_join(seedling_survival_long,seedling_data_sub,
                        by = c("uniqueID" = "uniqueID",
                               "campaign_number" = "campaign_number"))

# Backfill meta-data columns relating to site, block, plot etc
full_data <- full_data %>% 
  group_by(uniqueID, ) %>% 
  fill(species:plotID, .direction = "downup") %>% 
  ungroup()

# Copy veg heigh, moss cover etc data for a given year
# First create year col
full_data$year <- NA
full_data <- full_data %>% 
  mutate(year = ifelse(campaign_number == "zero" |
                         campaign_number == "first" |
                         campaign_number == "second" |
                         campaign_number == "third", "2020", "2021")) %>% 
  group_by(plotID, year) %>% 
  fill(vegetation_height:lichen_cover, .direction = "downup") %>% 
  ungroup()

# Backfill campaign dates
full_data <- full_data %>% 
  group_by(blockID, campaign_number) %>% 
  fill(date, .direction = "downup") %>% 
  ungroup()

# Order data and remove cols
full_data <- full_data %>% 
  select(uniqueID, species, siteID, blockID, experiment, OTC, vegetation, plotID,
         registrator, date, campaign_number, X, Y, present,
         vegetation_height, bryophyte_depth, vegetation_cover,
         bryophyte_cover, lichen_cover,
         comments)
  
# Save file
write.csv(full_data, "Data/Germination_field_experiment/cleaned/INCLINE_seedling_data.csv", row.names = FALSE)

```

